#!/bin/sh

if [ $# -eq 0 ]
  then
    echo "please supply a database name as an argument"
    exit
fi

fab ec2_down
if [ $? -ne 0 ]; then
    echo 'ec2_down failed. Terminating'
    exit
fi

fab ec2_up:db=$1
if [ $? -ne 0 ]; then
    echo 'ec2_down failed. Terminating'
    exit
fi


fab db_up:db=$1
if [ $? -ne 0 ]; then
    echo 'db_up failed. Terminating'
    exit
fi


fab ycsb_deploy
if [ $? -ne 0 ]; then
    echo 'ycsb_deploy failed. Terminating'
    exit
fi

fab ycsb_inittables:db=$1
if [ $? -ne 0 ]; then
    echo 'ycsb_inittables failed. Terminating'
    exit
fi

fab ycsb_load:db=$1
if [ $? -ne 0 ]; then
    echo 'ycsb_load failed. Terminating'
    exit
fi
