#!/bin/sh


if [ "$#" -ne 1 ]; then
    echo "you need 1 arguments for this script"
    exit 1
fi

aws ec2 describe-instances --filters "Name=tag-value,Values=$1" "Name=instance-state-name,Values=pending,running" | grep INSTANCES | awk  {'print $8'} | uniq
