#!/bin/sh


IDS=`aws ec2 describe-instances | grep INSTANCE | awk {'print $8'} | sort | uniq`
aws ec2 terminate-instances --instance-ids $IDS

echo "Giving instances 30s to terminate"
sleep 30

VOLS=`aws ec2 describe-volumes | grep VOLUMES | awk {'print $9'}`
echo "All Volumes: $VOLS"
for V in $VOLS
do
    OUT=`aws ec2 delete-volume --volume-id $V`
    echo "deleted volume: $V, output: $OUT"
done






